// "use client"
import type { Metadata } from "next";
import "./globals.css";
import "./root-styles.scss";
import Navbar from "@/components/navbar/Navbar";
import CustomCursor from "@/components/custom cursor/CustomCurosr";
import Footer from "@/components/footer/Footer";
import ReduxProvidor from "@/store/ReduxProvidor";
import ThemeSetter from "@/components/themSetter/ThemeSetter";


export const metadata: Metadata = {
  title: {
    default : "Mani Shop",
    template: "Mani Shop | %s"
  },
  // description: "Generated by create next app",
    icons: {
    icon: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

// export const metadata = {
//   title: "My App",
//   icons: {
//     icon: "/favicon.svg",
//     apple: "/apple-touch-icon.png",
//   },
// };


// const theme = localStorage.getItem("theme") === "dark" ? true : false

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className={`overflow-x-hidden`}>
        <ReduxProvidor>

          <ThemeSetter/>

          <CustomCursor />

          <div className="mb-20 ">
            <Navbar />
          </div>

          <div className="content z-2 pb-20 mb-100 relative min-h-screen">
            {children}
          </div>

          <div className="w-full h-100   footer fixed bottom-0 right-0 z-1">
            <Footer />
          </div>
        </ReduxProvidor>
      </body>
    </html>
  );
}
